name: fmdb
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pyyaml
  - tabulate
  - tqdm
  - jupyterlab
  - ipykernel
  - pytest
  - pytorch::pytorch
  - pytorch::pytorch-cuda=12.4
  - pip
  - pip:
      - anndata
      - phate
      - scanpy
      - pot
      - torchdiffeq
